version: '3'
dotenv: ['VERSION']
vars:
  APP_NAME: "nightshift"
  BIN_DIR: "$HOME/.local/bin"
  RELEASE_DIR: ".build/release"
  SWIFT_VERSION: "5.9"
tasks:
  run:
    cmds:
      - swift run {{.APP_NAME}}
    silent: true
  build:
    cmds:
      - swift build
    silent: true
  test:
    cmds:
      - swift test
    silent: true
  format:
    cmds:
      - swiftformat --swiftversion {{.SWIFT_VERSION}} Package.swift Sources
    silent: true
  lint:
    cmds:
      - swiftlint
    silent: true
  artifacts:
    deps: [lint]
    cmds:
      - swift build --configuration release --disable-sandbox --arch arm64
    silent: true
  install:
    requires:
      vars: [APP_NAME, BIN_DIR]
    deps: [artifacts]
    cmds:
      - mkdir -p "{{.BIN_DIR}}"
      - cp "{{.RELEASE_DIR}}/{{.APP_NAME}}" "{{.BIN_DIR}}"
  uninstall:
    requires:
      vars: [APP_NAME, BIN_DIR]
    cmds:
      - rm -rf "{{.BIN_DIR}}/{{.APP_NAME}}"
    silent: true
  tag:
    cmds:
      - git tag "$APP_VERSION"
      - git push origin "$APP_VERSION"
  release:
    deps: [tag]
    cmds:
      - gh auth status
      - gh release create --generate-notes "$APP_VERSION"
  sha:
    cmds:
      - curl -sL "https://github.com/oschrenk/nightshift.swift/archive/refs/tags/$APP_VERSION.tar.gz" | shasum -a 256
  clean:
    cmds:
      - rm -rf .build
    silent: true
